#######################################
#          Mercenay Mode V5           #
# Add a 'mercenary' option to your Z3 #
# section to use this trigger block   #
#######################################
triggers:
  ### Start Mecenary mode trigger block ###
  # check to see if our goal is mecenary mode
  - option_name: goals
    option_result: mercenary
    option_category: A Link to the Past
    options:
      # add the required plando stuff so the generation will fail if these are not turned on.
      requires:
        plando: items, texts
      # convert the game into a 1/1 TFH
      A Link to the Past:
        goals: triforce_hunt
        triforce_pieces_mode: available
        triforce_pieces_available: 1
        triforce_pieces_required: 1
        # pick what arena we want to plando the triforce piece to feel free to edit these weights.
        mercenary_boss_location:
          eastern_palace: 1
          desert_palace: 1
          tower_of_hera: 1
          palace_of_darkness: 1
          ice_palace: 1
          swamp_palace: 1
          misery_mire: 1
          thieves_town: 1
          skull_woods: 1
          turtle_rock: 1
  # plant the triforce piece on the selected boss and then planod the text to the man at the bar in kakariko tavern.
  - option_name: mercenary_boss_location
    option_result: eastern_palace
    option_category: A Link to the Past
    options:
      A Link to the Past:
        plando_items:
          - item:
              Triforce Piece: 1
            location: Eastern Palace - Boss
        plando_texts:
          - text: "hey @\nYour quarry slumbers behind sentinels of stone."
            at: kakariko_tavern_fisherman
          - text: "A hit has been put out on one of Ganon's generals."
            at: sign_ganon
  - option_name: mercenary_boss_location
    option_result: desert_palace
    option_category: A Link to the Past
    options:
      A Link to the Past:
        plando_items:
          - item:
              Triforce Piece: 1
            location: Desert Palace - Boss
        plando_texts:
          - text: "hey @\nYour prey lurks amidst the shifting sands."
            at: kakariko_tavern_fisherman
          - text: "A hit has been put out on one of Ganon's generals."
            at: sign_ganon
  - option_name: mercenary_boss_location
    option_result: tower_of_hera
    option_category: A Link to the Past
    options:
      A Link to the Past:
        plando_items:
          - item:
              Triforce Piece: 1
            location: Tower of Hera - Boss
        plando_texts:
          - text: "hey @\nYour mark sits at the pinnacle of the realm."
            at: kakariko_tavern_fisherman
          - text: "A hit has been put out on one of Ganon's generals."
            at: sign_ganon
  - option_name: mercenary_boss_location
    option_result: palace_of_darkness
    option_category: A Link to the Past
    options:
      A Link to the Past:
        plando_items:
          - item:
              Triforce Piece: 1
            location: Palace of Darkness - Boss
        plando_texts:
          - text: "hey @\nYou must kill the one upon the pitch black throne."
            at: kakariko_tavern_fisherman
          - text: "A hit has been put out on one of Ganon's generals."
            at: sign_ganon
  - option_name: mercenary_boss_location
    option_result: swamp_palace
    option_category: A Link to the Past
    options:
      A Link to the Past:
        plando_items:
          - item:
              Triforce Piece: 1
            location: Swamp Palace - Boss
        plando_texts:
          - text: "hey @\nYour target is in need of a plumber."
            at: kakariko_tavern_fisherman
          - text: "A hit has been put out on one of Ganon's generals."
            at: sign_ganon
  - option_name: mercenary_boss_location
    option_result: skull_woods
    option_category: A Link to the Past
    options:
      A Link to the Past:
        plando_items:
          - item:
              Triforce Piece: 1
            location: Skull Woods - Boss
        plando_texts:
          - text: "hey @\nYour nemesis lies within the skull of a long dead beast."
            at: kakariko_tavern_fisherman
          - text: "A hit has been put out on one of Ganon's generals."
            at: sign_ganon
  - option_name: mercenary_boss_location
    option_result: thieves_town
    option_category: A Link to the Past
    options:
      A Link to the Past:
        plando_items:
          - item:
              Triforce Piece: 1
            location: Thieves' Town - Boss
        plando_texts:
          - text: "hey @\nYour mark schemes within a den of evil."
            at: kakariko_tavern_fisherman
          - text: "A hit has been put out on one of Ganon's generals."
            at: sign_ganon
  - option_name: mercenary_boss_location
    option_result: ice_palace
    option_category: A Link to the Past
    options:
      A Link to the Past:
        plando_items:
          - item:
              Triforce Piece: 1
            location: Ice Palace - Boss
        plando_texts:
          - text: "hey @\nYour enemy sleeps beneath the frozen depths."
            at: kakariko_tavern_fisherman
          - text: "A hit has been put out on one of Ganon's generals."
            at: sign_ganon
  - option_name: mercenary_boss_location
    option_result: misery_mire
    option_category: A Link to the Past
    options:
      A Link to the Past:
        plando_items:
          - item:
              Triforce Piece: 1
            location: Misery Mire - Boss
        plando_texts:
          - text: "hey @\nYour target watches from a viscid lair."
            at: kakariko_tavern_fisherman
          - text: "A hit has been put out on one of Ganon's generals."
            at: sign_ganon
  - option_name: mercenary_boss_location
    option_result: turtle_rock
    option_category: A Link to the Past
    options:
      A Link to the Past:
        plando_items:
          - item:
              Triforce Piece: 1
            location: Turtle Rock - Boss
        plando_texts:
          - text: "hey @\nYour quarry rests within a beast of stone."
            at: kakariko_tavern_fisherman
          - text: "A hit has been put out on one of Ganon's generals."
            at: sign_ganon
### END Mercenay mode triggerb block ###